# Generated by Django 5.0.7 on 2024-07-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='김철수', max_length=50),
        ),
    ]
