# Generated by Django 5.0.7 on 2024-07-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logData',
            field=models.BooleanField(default=False),
        ),
    ]
