# Generated by Django 5.0.7 on 2024-07-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_user_logdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logData',
        ),
    ]
