# Generated by Django 5.0.7 on 2024-07-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='방문자', max_length=50),
        ),
    ]
